version: '2'
services:
    db:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=vspeed
          - MYSQL_DATABASE=docker
          - MYSQL_USER=jskowr
          - MYSQL_PASSWORD=vspeed
        ports:
          - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            PMA_PORT: 3306
            PMA_HOST: db
            MYSQL_USER: jskowr
            MYSQL_PASSWORD: vspeed
            MYSQL_ROOT_PASSWORD: vspeed
        depends_on:
            - db        
    website:
        container_name: php_template
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-enabled/vhost.conf
        ports:
            - 80:80
        depends_on:
            - db