version: '2'
services:
    db:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=vspeed
          - MYSQL_DATABASE=docker
          - MYSQL_USER=jskowr
          - MYSQL_PASSWORD=vspeed
        ports:
          - "8082:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: jskowr
            MYSQL_PASSWORD: vspeed
            MYSQL_ROOT_PASSWORD: vspeed        
    website:
        container_name: php72
        build:
            context: ./
        volumes:
            - ../src:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - db